modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="tipthescales" #mandatory
version="${file.jarVersion}" #mandatory
displayName="TipTheScales" #mandatory
authors="Jaredlll08"
updateJSONURL="https://updates.blamejared.com/get?n=TipTheScales&gv=1.16.2"
description='''
Allows for more control when adjusting the GUI size.
'''