modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="tipthescales" #mandatory
version="${file.jarVersion}" #mandatory
displayName="TipTheScales" #mandatory
authors="Jaredlll08"
description='''
Allows for more control when adjusting the GUI size.
'''